<a href="https://colab.research.google.com/github/Maddox159-crypto/2026_ESAA_assignment/blob/main/%ED%95%84%EC%82%AC31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[개념]

## 1.1 인공지능, 머신 러닝과 딥러닝

인공지능 > 머신 러닝 > 딥러닝 (포함 관계)

- 머신 러닝: 데이터의 특성 추출을 사람이 직접 해 줘야 하고, 컴퓨터는 분류만 담당
- 딥러닝: 특성 추출부터 분류까지 신경망이 알아서 처리

차이점
- 데이터: 머신 러닝은 수천 개면 되는데 딥러닝은 수백만 개 이상 필요
- 훈련 시간: 머신 러닝은 짧고 딥러닝은 김
- 결과: 머신 러닝은 점수나 분류 같은 숫자 값, 딥러닝은 텍스트, 소리 등 뭐든 가능

## 1.3.1 딥러닝 학습 과정

데이터 → 모델 정의 → 모델 컴파일 → 모델 훈련 → 모델 예측

- 모델 정의: 신경망 생성. 은닉층이 많을수록 성능은 좋아지지만 과적합 위험도 커짐
- 모델 컴파일: 활성화 함수, 손실 함수, 옵티마이저 선택
- 모델 훈련: 배치 크기와 에포크 정하고, 파라미터/하이퍼파라미터 최적값 찾기
- 모델 예측: 검증 데이터로 예측해 보고, 예측력이 낮으면 튜닝하거나 신경망 재설계

배치는 한 번에 처리하는 데이터 묶음, 에포크는 전체 데이터를 훈련하는 횟수.
예: 데이터 1000개, 배치 20, 에포크 10이면 1에포크에 50번 업데이트, 총 500번 업데이트

## 2.2.5 모델 훈련

학습 = $y = wx + b$ 에서 오차가 가장 작아지는 $w$, $b$ 찾기.

파이토치 학습 순서
1. 모델, 손실 함수, 옵티마이저 정의
2. optimizer.zero_grad() : 기울기 초기화
3. output = model(input) : 출력 계산
4. loss = loss_fn(output, target) : 오차 계산
5. loss.backward() : 역전파
6. optimizer.step() : 파라미터 업데이트

loss.backward()는 기울기를 누적시키기 때문에 매번 zero_grad()로 0으로 만들어야 함.
(RNN처럼 누적이 필요한 모델은 예외)

[필사]

In [2]:
import torch
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]], device="cuda:0"))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))


tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print('--------------------')
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
--------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [5]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3,4, 6])
print(w-v)

tensor([2, 2, 3])


In [8]:
temp = torch.tensor([
    [1,2], [3,4]
])
print(temp.shape)
print('------------------')
print(temp.view(4, 1))
print('-----------------')
print(temp.view(-1))
print('-----------------')
print(temp.view(1, -1))
print('-----------------')
print(temp.view(-1, 1))
print('-----------------')
print(temp.view(-1, 1))

torch.Size([2, 2])
------------------
tensor([[1],
        [2],
        [3],
        [4]])
-----------------
tensor([1, 2, 3, 4])
-----------------
tensor([[1, 2, 3, 4]])
-----------------
tensor([[1],
        [2],
        [3],
        [4]])
-----------------
tensor([[1],
        [2],
        [3],
        [4]])


In [ ]:
#46
# import pandas as pd
# import torch
#
# data = pd.read_csv('../class2.csv')
#
# x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
# y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

#47
# import pandas as pd
# import torch
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader
#
# class CustomDataset(Dataset):
#     def __init__(self, csv_file):
#         self.label = pd.read_csv(csv_file)
#
#     def __len__(self):
#         return len(self.label)
#
#     def __getitem__(self, idx):
#         sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
#         label = torch.tensor(self.label.iloc[idx, 3]).int()
#         return sample, label
#
# tensor_dataset = CustomDataset('../covtype.csv')
# dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)

#48
# for i, data in enumerate(dataset, 0):
#     print(i, end='')
#     batch = data[0]
#     print(batch.size())

# 49
# import torchvision.transforms as transforms
#
# mnist_transform = transforms.Compose([
#     transforms.ToTensor(),
#     transforms.Normalize((0.5,), (1.0,))
# ])
#
# from torchvision.datasets import MNIST
# import requests
# download_root = '../chap02/data/MNIST_DATASET'
#
# train_dataset = MNIST(download_root, transform=mnist_transform, train=True,
#                       download=True)
# valid_dataset = MNIST(download_root, transform=mnist_transform, train=False,
#                       download=True)
# test_dataset = MNIST(download_root, transform=mnist_transform, train=False,
#                      download=True)


# 50
# model = nn.Linear(in_features=1, out_features=1, bias=True)


#51
# class MLP(Module):
#     def __init__(self, inputs):
#         super(MLP, self).__init__()
#         self.layer = Linear(inputs, 1)
#         self.activation = Sigmoid()
#
#     def forward(self, X):
#         X = self.layer(X)
#         X = self.activation(X)
#         return X


In [9]:
!pip install requests

In [11]:
# model = nn.Linear(in_features=1 , out_features=1 , bias=True)

In [12]:
import torch.nn as nn
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels = 3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace= True),
            nn.MaxPool2d(2))
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels = 64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace= True),
            nn.MaxPool2d(2))
        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True))
        def forward(self, x):
            x = self.layer1(x)
            x = self.layer2(x)
            x = x.view(x.size[0], -1)
            x = self.layer3(x)
            return x
model = MLP()

print("Printing children\n----------")
print(list(model.children()))
print("\n\nPrinting Modules\n-----------------")
print(list(model.modules()))

Printing children
----------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-----------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=750, out_features=1

In [13]:
def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features = in_features, out_features = hidden_features)
    activation = nn.Tanh()
    output = nn.Linear(in_features = hidden_features, out_features = out_features)
    net = nn.Sequential(hidden, activation, output)
    return net



In [ ]:
#56
# from torch.optim import optimizer
# criterion = torch.nn.MSELoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
# scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer,
#                                               lr_lambda=lambda epoch: 0.95 ** epoch)
# for epoch in range(1, 100+1):
#     for x, y in dataloader:
#         optimizer.zero_grad()
#         loss_fn(model(x), y).backward()
#         optimizer.step()
#     scheduler.step()


#57
# for epoch in range(100):
#     yhat = model(x_train)
#     loss = criterion(yhat, y_train)
#     optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()

In [14]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 21.4 MB/s eta 0:00:00


In [15]:
import torch
import torchmetrics

In [17]:
preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10, ))
acc = torchmetrics.functional.accuracy(preds, target, task='multiclass', num_classes=5)


In [18]:
import torch
import torchmetrics
metric = torchmetrics.Accuracy(task='multiclass', num_classes=5)
n_batches = 10
for i in range(n_batches):
    preds = torch.randn(10, 5).softmax(dim=-1)
    target = torch.randint(5, (10, ))
    metric.update(preds, target)
    acc = metric(preds, target)
    print(f"Accuracy on batch {i}: {acc}")
acc = metric.compute()
print(f"Overall accuracy: {acc}")

Accuracy on batch 0: 0.30000001192092896
Accuracy on batch 1: 0.30000001192092896
Accuracy on batch 2: 0.10000000149011612
Accuracy on batch 3: 0.30000001192092896
Accuracy on batch 4: 0.10000000149011612
Accuracy on batch 5: 0.10000000149011612
Accuracy on batch 6: 0.30000001192092896
Accuracy on batch 7: 0.30000001192092896
Accuracy on batch 8: 0.10000000149011612
Accuracy on batch 9: 0.10000000149011612
Overall accuracy: 0.20000000298023224


In [ ]:
# 59
# import torch
# from torch.utils.tensorboard import SummaryWriter
# writer = SummaryWriter("../chap02/tensorboard")
#
# for epoch in range(num_epochs):
#     model.train()
#     batch_loss = 0.0
#
#     for i, (x, y) in enumerate(dataloader):
#         x, y = x.to(device).float(), y.to(device).float()
#         outputs = model(x)
#         loss = criterion(outputs, y)
#         writer.add_scalar("Loss", loss, epoch)
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()
#
# writer.close()


# 60
# model.eval()
# with torch.no_grad():
#     valid_loss = 0
#     for x, y in valid_dataloader:
#         outputs = model(x)
#         loss = F.cross_entropy(outputs, y.long().squeeze())
#         valid_loss += float(loss)
#         y_hat += [outputs]
#
# valid_loss = valid_loss / len(valid_loader)